# -*- coding: utf-8 -*-
import os
class BlockConfig:
    default_blocklist_path = os.path.expanduser('~/.config/dnsblock/dnsblock_source.txt')
    repo_url = '# https://github.com/swills1/python-dnsblock\n'
    generated_comment_lead = '# Generated by dnsblock for '
    generated_datetime_format = ' on %Y%m%d at %H:%M:%S\n'
    unbound_conf_lead_string = 'server:\n'
    dns_app_dict = {
        "dnsmasq": "Dnsmasq",
        "unbound": "Unbound",
    }
