DEFAULT_SOURCE_PATH = '~/.config/dnsblock/dnsblock_source.txt'
REPO_URL = '# https://github.com/swills1/python-dnsblock\n'
GENERATED_COMMENT_LEAD = '# Generated by dnsblock for '
GENERATED_DATETIME_FORMAT = ' on %Y%m%d at %H:%M:%S\n'
LEADSTRING_DICT = {
    "unbound": "server:\n"
}
DNS_APP_DICT = {
    "dnsmasq": ('address=/','/'),
    "unbound": ('local-zone: "','" redirect'),
}

